-- MySQL Script generated by MySQL Workbench
-- 12/03/15 08:45:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cpanet1_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cpanet1_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cpanet1_db` DEFAULT CHARACTER SET utf8mb4 ;
USE `cpanet1_db` ;

-- -----------------------------------------------------
-- Table `cpanet1_db`.`x_grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpanet1_db`.`x_grupos` (
  `ug_id_pk` INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ug_nombre_vc` VARCHAR(20) NULL DEFAULT NULL,
  `ug_notas_tx` TEXT NULL DEFAULT NULL,
  `ug_clientes` INT(6) NULL DEFAULT NULL,
  `x_cuenta_ac_id_pk` INT(6) UNSIGNED NOT NULL,
  PRIMARY KEY (`ug_id_pk`, `x_cuenta_ac_id_pk`),
  INDEX `fk_x_grupos_x_cuenta1_idx` (`x_cuenta_ac_id_pk` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cpanet1_db`.`x_paquetes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpanet1_db`.`x_paquetes` (
  `pk_id_pk` INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `pk_nombre_vc` VARCHAR(30) CHARACTER SET 'latin1' COLLATE 'latin1_general_ci' NULL DEFAULT NULL,
  `pk_habilitaphp_in` INT(1) NULL DEFAULT '0',
  `pk_habilitacgi_in` INT(1) NULL DEFAULT '0',
  `pk_creado_ts` INT(30) NULL DEFAULT NULL,
  `pk_borrado_ts` INT(30) NULL DEFAULT NULL,
  `x_cuenta_ac_id_pk` INT(6) UNSIGNED NOT NULL,
  PRIMARY KEY (`pk_id_pk`, `x_cuenta_ac_id_pk`),
  INDEX `fk_x_paquetes_x_cuenta1_idx` (`x_cuenta_ac_id_pk` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cpanet1_db`.`x_cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpanet1_db`.`x_cuenta` (
  `ac_id_pk` INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ac_usuario_vc` VARCHAR(50) NULL DEFAULT NULL,
  `ac_clave_vc` VARCHAR(200) NULL DEFAULT NULL,
  `ac_correo_vc` VARCHAR(250) NULL DEFAULT NULL,
  `ac_temausuario_vc` VARCHAR(45) NULL DEFAULT NULL,
  `ac_usuariocss_vc` VARCHAR(45) NULL DEFAULT NULL,
  `ac_habilitado_in` INT(1) NULL DEFAULT '1',
  `ac_ultimoinicio_ts` INT(30) NULL DEFAULT NULL,
  `ac_anuncio_tx` TEXT NULL DEFAULT NULL,
  `ac_resethash_tx` TEXT NULL DEFAULT NULL,
  `ac_clavesalt_vc` VARCHAR(22) NULL DEFAULT NULL,
  `ac_catorden_vc` VARCHAR(255) NULL DEFAULT NULL,
  `ac_creado_ts` INT(30) NULL DEFAULT NULL,
  `ac_borrado_ts` INT(30) NULL DEFAULT NULL,
  `x_grupos_ug_id_pk` INT(6) UNSIGNED NOT NULL,
  `x_grupos_x_cuenta_ac_id_pk` INT(6) UNSIGNED NOT NULL,
  `x_paquetes_pk_id_pk` INT(6) UNSIGNED NOT NULL,
  `x_paquetes_x_cuenta_ac_id_pk` INT(6) UNSIGNED NOT NULL,
  PRIMARY KEY (`ac_id_pk`, `x_grupos_ug_id_pk`, `x_grupos_x_cuenta_ac_id_pk`, `x_paquetes_pk_id_pk`, `x_paquetes_x_cuenta_ac_id_pk`),
  INDEX `fk_x_cuenta_x_grupos1_idx` (`x_grupos_ug_id_pk` ASC, `x_grupos_x_cuenta_ac_id_pk` ASC),
  INDEX `fk_x_cuenta_x_paquetes1_idx` (`x_paquetes_pk_id_pk` ASC, `x_paquetes_x_cuenta_ac_id_pk` ASC),
  CONSTRAINT `fk_x_cuenta_x_grupos1`
    FOREIGN KEY (`x_grupos_ug_id_pk` , `x_grupos_x_cuenta_ac_id_pk`)
    REFERENCES `cpanet1_db`.`x_grupos` (`ug_id_pk` , `x_cuenta_ac_id_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_x_cuenta_x_paquetes1`
    FOREIGN KEY (`x_paquetes_pk_id_pk` , `x_paquetes_x_cuenta_ac_id_pk`)
    REFERENCES `cpanet1_db`.`x_paquetes` (`pk_id_pk` , `x_cuenta_ac_id_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cpanet1_db`.`x_alias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpanet1_db`.`x_alias` (
  `al_id_pk` INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `al_direccion_vc` VARCHAR(255) NULL DEFAULT NULL,
  `al_destino_vc` VARCHAR(255) NULL DEFAULT NULL,
  `al_crear_ts` INT(30) NULL DEFAULT NULL,
  `al_borrar_ts` INT(30) NULL DEFAULT NULL,
  `x_cuenta_ac_id_pk` INT(6) UNSIGNED NOT NULL,
  PRIMARY KEY (`al_id_pk`, `x_cuenta_ac_id_pk`),
  INDEX `fk_x_alias_x_cuenta1_idx` (`x_cuenta_ac_id_pk` ASC),
  CONSTRAINT `fk_x_alias_x_cuenta1`
    FOREIGN KEY (`x_cuenta_ac_id_pk`)
    REFERENCES `cpanet1_db`.`x_cuenta` (`ac_id_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cpanet1_db`.`x_anchobanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpanet1_db`.`x_anchobanda` (
  `bd_id_pk` INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `bd_mes_in` INT(6) NULL DEFAULT NULL,
  `bd_transmonto_bi` BIGINT(20) NULL DEFAULT NULL,
  `bd_montodisco_bi` BIGINT(20) NULL DEFAULT NULL,
  `bd_sobredisco_in` INT(6) NULL DEFAULT NULL,
  `bd_encuestadisco_in` INT(6) NULL DEFAULT NULL,
  `bd_sobretrans_in` INT(6) NULL DEFAULT NULL,
  `bd_encuestatrans_in` INT(6) NULL DEFAULT NULL,
  `x_cuenta_ac_id_pk` INT(6) UNSIGNED NOT NULL,
  PRIMARY KEY (`bd_id_pk`, `x_cuenta_ac_id_pk`),
  INDEX `fk_x_anchobanda_x_cuenta1_idx` (`x_cuenta_ac_id_pk` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cpanet1_db`.`x_crontareas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpanet1_db`.`x_crontareas` (
  `ct_id_pk` INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ct_script_vc` VARCHAR(255) NULL DEFAULT NULL,
  `ct_sincronizacion_vc` VARCHAR(255) NULL DEFAULT NULL,
  `ct_caminocompleto_vc` VARCHAR(255) NULL DEFAULT NULL,
  `ct_descripcion_tx` TEXT NULL DEFAULT NULL,
  `ct_creado_ts` INT(30) NULL DEFAULT NULL,
  `ct_borrado_ts` INT(30) NULL DEFAULT NULL,
  `x_cuenta_ac_id_pk` INT(6) UNSIGNED NOT NULL,
  PRIMARY KEY (`ct_id_pk`, `x_cuenta_ac_id_pk`),
  INDEX `fk_x_crontareas_x_cuenta1_idx` (`x_cuenta_ac_id_pk` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cpanet1_db`.`x_listasdist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpanet1_db`.`x_listasdist` (
  `dl_id_pk` INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `dl_direccion_vc` VARCHAR(255) NULL DEFAULT NULL,
  `dl_creada_ts` INT(30) NULL DEFAULT NULL,
  `dl_borrada_ts` INT(30) NULL DEFAULT NULL,
  `x_cuenta_ac_id_pk` INT(6) UNSIGNED NOT NULL,
  `x_cuenta_x_grupos_ug_id_pk` INT(6) UNSIGNED NOT NULL,
  `x_cuenta_x_grupos_x_cuenta_ac_id_pk` INT(6) UNSIGNED NOT NULL,
  `x_cuenta_x_paquetes_pk_id_pk` INT(6) UNSIGNED NOT NULL,
  `x_cuenta_x_paquetes_x_cuenta_ac_id_pk` INT(6) UNSIGNED NOT NULL,
  PRIMARY KEY (`dl_id_pk`, `x_cuenta_ac_id_pk`, `x_cuenta_x_grupos_ug_id_pk`, `x_cuenta_x_grupos_x_cuenta_ac_id_pk`, `x_cuenta_x_paquetes_pk_id_pk`, `x_cuenta_x_paquetes_x_cuenta_ac_id_pk`),
  INDEX `fk_x_listasdist_x_cuenta1_idx` (`x_cuenta_ac_id_pk` ASC, `x_cuenta_x_grupos_ug_id_pk` ASC, `x_cuenta_x_grupos_x_cuenta_ac_id_pk` ASC, `x_cuenta_x_paquetes_pk_id_pk` ASC, `x_cuenta_x_paquetes_x_cuenta_ac_id_pk` ASC),
  CONSTRAINT `fk_x_listasdist_x_cuenta1`
    FOREIGN KEY (`x_cuenta_ac_id_pk` , `x_cuenta_x_grupos_ug_id_pk` , `x_cuenta_x_grupos_x_cuenta_ac_id_pk` , `x_cuenta_x_paquetes_pk_id_pk` , `x_cuenta_x_paquetes_x_cuenta_ac_id_pk`)
    REFERENCES `cpanet1_db`.`x_cuenta` (`ac_id_pk` , `x_grupos_ug_id_pk` , `x_grupos_x_cuenta_ac_id_pk` , `x_paquetes_pk_id_pk` , `x_paquetes_x_cuenta_ac_id_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cpanet1_db`.`x_usuarioslistdist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpanet1_db`.`x_usuarioslistdist` (
  `du_id_pk` INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `du_direccion_vc` VARCHAR(255) NULL DEFAULT NULL,
  `du_creado_ts` INT(30) NULL DEFAULT NULL,
  `du_borrado_ts` INT(30) NULL DEFAULT NULL,
  `x_listasdist_dl_id_pk` INT(6) UNSIGNED NOT NULL,
  PRIMARY KEY (`du_id_pk`, `x_listasdist_dl_id_pk`),
  INDEX `fk_x_usuarioslistdist_x_listasdist_idx` (`x_listasdist_dl_id_pk` ASC),
  CONSTRAINT `fk_x_usuarioslistdist_x_listasdist`
    FOREIGN KEY (`x_listasdist_dl_id_pk`)
    REFERENCES `cpanet1_db`.`x_listasdist` (`dl_id_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cpanet1_db`.`x_vhosts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpanet1_db`.`x_vhosts` (
  `vh_id_pk` INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `vh_nombre_vc` VARCHAR(255) CHARACTER SET 'latin1' COLLATE 'latin1_general_ci' NULL DEFAULT NULL,
  `vh_directorio_vc` VARCHAR(255) CHARACTER SET 'latin1' COLLATE 'latin1_general_ci' NULL DEFAULT NULL,
  `vh_tipo_in` INT(1) NULL DEFAULT '1',
  `vh_activo_in` INT(1) NULL DEFAULT '0',
  `vh_suhosin_in` INT(1) NULL DEFAULT '1',
  `vh_obasedir_in` INT(1) NULL DEFAULT '1',
  `vh_dedicado_tx` TEXT NULL DEFAULT NULL,
  `vh_puerto_dedicado_in` INT(6) NULL DEFAULT NULL,
  `vh_ip_dedicada_vc` VARCHAR(45) NULL DEFAULT NULL,
  `vh_puerto_reenvio_in` INT(1) NULL DEFAULT NULL,
  `vh_habilitada_in` INT(1) NULL DEFAULT '1',
  `vh_creado_ts` INT(30) NULL DEFAULT NULL,
  `vh_deleted_ts` INT(30) NULL DEFAULT NULL,
  `x_dns_dn_id_pk` INT(6) UNSIGNED NOT NULL,
  `x_dns_x_cuenta_ac_id_pk` INT(6) UNSIGNED NOT NULL,
  PRIMARY KEY (`vh_id_pk`, `x_dns_dn_id_pk`, `x_dns_x_cuenta_ac_id_pk`),
  INDEX `fk_x_vhosts_x_dns1_idx` (`x_dns_dn_id_pk` ASC, `x_dns_x_cuenta_ac_id_pk` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cpanet1_db`.`x_dns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpanet1_db`.`x_dns` (
  `dn_id_pk` INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `dn_nombre_vc` VARCHAR(255) NULL DEFAULT NULL,
  `dn_tipo_vc` VARCHAR(50) NULL DEFAULT NULL,
  `dn_host_vc` VARCHAR(100) NULL DEFAULT NULL,
  `dn_ttl_in` INT(30) NULL DEFAULT NULL,
  `dn_objetivo_vc` VARCHAR(100) NULL DEFAULT NULL,
  `dn_textobjetivo_tx` TEXT NULL DEFAULT NULL,
  `dn_prioridad_in` INT(50) NULL DEFAULT NULL,
  `dn_peso_in` INT(50) NULL DEFAULT NULL,
  `dn_puerto_in` INT(50) NULL DEFAULT NULL,
  `dn_creado_ts` INT(30) NULL DEFAULT NULL,
  `dn_borrado_ts` INT(30) NULL DEFAULT NULL,
  `x_cuenta_ac_id_pk` INT(6) UNSIGNED NOT NULL,
  `x_vhosts_vh_id_pk` INT(6) UNSIGNED NOT NULL,
  `x_vhosts_x_dns_dn_id_pk` INT(6) UNSIGNED NOT NULL,
  `x_vhosts_x_dns_x_cuenta_ac_id_pk` INT(6) UNSIGNED NOT NULL,
  PRIMARY KEY (`dn_id_pk`, `x_cuenta_ac_id_pk`, `x_vhosts_vh_id_pk`, `x_vhosts_x_dns_dn_id_pk`, `x_vhosts_x_dns_x_cuenta_ac_id_pk`),
  INDEX `fk_x_dns_x_cuenta1_idx` (`x_cuenta_ac_id_pk` ASC),
  INDEX `fk_x_dns_x_vhosts1_idx` (`x_vhosts_vh_id_pk` ASC, `x_vhosts_x_dns_dn_id_pk` ASC, `x_vhosts_x_dns_x_cuenta_ac_id_pk` ASC),
  CONSTRAINT `fk_x_dns_x_cuenta1`
    FOREIGN KEY (`x_cuenta_ac_id_pk`)
    REFERENCES `cpanet1_db`.`x_cuenta` (`ac_id_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_x_dns_x_vhosts1`
    FOREIGN KEY (`x_vhosts_vh_id_pk` , `x_vhosts_x_dns_dn_id_pk` , `x_vhosts_x_dns_x_cuenta_ac_id_pk`)
    REFERENCES `cpanet1_db`.`x_vhosts` (`vh_id_pk` , `x_dns_dn_id_pk` , `x_dns_x_cuenta_ac_id_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cpanet1_db`.`x_ayuda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpanet1_db`.`x_ayuda` (
  `fq_id_pk` INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `fq_pregunta_tx` TEXT NULL DEFAULT NULL,
  `fq_respuesta_tx` TEXT NULL DEFAULT NULL,
  `fq_global_in` INT(1) NULL DEFAULT NULL,
  `fq_creado_ts` INT(30) NULL DEFAULT NULL,
  `fq_borrado_ts` INT(30) NULL DEFAULT NULL,
  `x_cuenta_ac_id_pk` INT(6) UNSIGNED NOT NULL,
  PRIMARY KEY (`fq_id_pk`, `x_cuenta_ac_id_pk`),
  INDEX `fk_x_ayuda_x_cuenta1_idx` (`x_cuenta_ac_id_pk` ASC),
  CONSTRAINT `fk_x_ayuda_x_cuenta1`
    FOREIGN KEY (`x_cuenta_ac_id_pk`)
    REFERENCES `cpanet1_db`.`x_cuenta` (`ac_id_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cpanet1_db`.`x_reenvios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpanet1_db`.`x_reenvios` (
  `fw_id_pk` INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `fw_direccion_vc` VARCHAR(255) NULL DEFAULT NULL,
  `fw_destino_vc` VARCHAR(255) NULL DEFAULT NULL,
  `fw_mantenrmensaje_in` INT(1) NULL DEFAULT '1',
  `fw_creado_ts` INT(30) NULL DEFAULT NULL,
  `fw_borrado_ts` INT(30) NULL DEFAULT NULL,
  `x_cuenta_ac_id_pk` INT(6) UNSIGNED NOT NULL,
  PRIMARY KEY (`fw_id_pk`, `x_cuenta_ac_id_pk`),
  INDEX `fk_x_forwarders_x_cuenta1_idx` (`x_cuenta_ac_id_pk` ASC),
  CONSTRAINT `fk_x_forwarders_x_cuenta1`
    FOREIGN KEY (`x_cuenta_ac_id_pk`)
    REFERENCES `cpanet1_db`.`x_cuenta` (`ac_id_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cpanet1_db`.`x_ftpcuentas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpanet1_db`.`x_ftpcuentas` (
  `ft_id_pk` INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ft_acc_fk` INT(6) NULL DEFAULT NULL,
  `ft_usuario_vc` VARCHAR(20) NULL DEFAULT NULL,
  `ft_directorio_vc` VARCHAR(255) NULL DEFAULT NULL,
  `ft_acceso_vc` VARCHAR(20) NULL DEFAULT NULL,
  `ft_clave_vc` VARCHAR(50) NULL DEFAULT NULL,
  `ft_creada_ts` INT(6) NULL DEFAULT NULL,
  `ft_borrada_ts` INT(6) NULL DEFAULT NULL,
  `x_cuenta_ac_id_pk` INT(6) UNSIGNED NOT NULL,
  PRIMARY KEY (`ft_id_pk`, `x_cuenta_ac_id_pk`),
  INDEX `fk_x_ftpcuentas_x_cuenta1_idx` (`x_cuenta_ac_id_pk` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cpanet1_db`.`x_htaccess`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpanet1_db`.`x_htaccess` (
  `ht_id_pk` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ht_cuenta_fk` INT(6) NULL DEFAULT NULL,
  `ht_usuario_vc` VARCHAR(10) NULL DEFAULT NULL,
  `ht_dir_vc` VARCHAR(255) NULL DEFAULT NULL,
  `ht_creado_ts` INT(30) NULL DEFAULT NULL,
  `ht_borrado_ts` INT(30) NULL DEFAULT NULL,
  `x_cuenta_ac_id_pk` INT(6) UNSIGNED NOT NULL,
  PRIMARY KEY (`ht_id_pk`, `x_cuenta_ac_id_pk`),
  INDEX `fk_x_htaccess_x_cuenta1_idx` (`x_cuenta_ac_id_pk` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cpanet1_db`.`x_logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpanet1_db`.`x_logs` (
  `lg_id_pk` INT(9) UNSIGNED NOT NULL AUTO_INCREMENT,
  `lg_usuario` INT(6) NOT NULL DEFAULT '1',
  `lg_codigo_vc` VARCHAR(10) NULL,
  `lg_modulo_vc` VARCHAR(25) NULL DEFAULT NULL,
  `lg_detalle_tx` TEXT NULL DEFAULT NULL,
  `lg_pila_tx` TEXT NULL,
  `lg_fecha_ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `x_cuenta_ac_id_pk` INT(6) UNSIGNED NOT NULL DEFAULT '1',
  PRIMARY KEY (`lg_id_pk`, `x_cuenta_ac_id_pk`),
  INDEX `fk_x_logs_x_cuenta1_idx` (`x_cuenta_ac_id_pk` ASC),
  CONSTRAINT `fk_x_logs_x_cuenta1`
    FOREIGN KEY (`x_cuenta_ac_id_pk`)
    REFERENCES `cpanet1_db`.`x_cuenta` (`ac_id_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 19909
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cpanet1_db`.`x_buzoncorreos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpanet1_db`.`x_buzoncorreos` (
  `mb_id_pk` INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `mb_direccion_vc` VARCHAR(255) NULL DEFAULT NULL,
  `mb_habilitado_in` INT(1) NULL DEFAULT '1',
  `mb_creado_ts` INT(30) NULL DEFAULT NULL,
  `mb_borrado_ts` INT(30) NULL DEFAULT NULL,
  `x_cuenta_ac_id_pk` INT(6) UNSIGNED NOT NULL,
  PRIMARY KEY (`mb_id_pk`, `x_cuenta_ac_id_pk`),
  INDEX `fk_x_mailboxes_x_cuenta1_idx` (`x_cuenta_ac_id_pk` ASC),
  CONSTRAINT `fk_x_mailboxes_x_cuenta1`
    FOREIGN KEY (`x_cuenta_ac_id_pk`)
    REFERENCES `cpanet1_db`.`x_cuenta` (`ac_id_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cpanet1_db`.`x_modcat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpanet1_db`.`x_modcat` (
  `mc_id_pk` INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `mc_nombre_vc` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`mc_id_pk`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cpanet1_db`.`x_modulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpanet1_db`.`x_modulos` (
  `mo_id_pk` INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `mo_nombre_vc` VARCHAR(200) NOT NULL,
  `mo_version_in` INT(10) NULL DEFAULT NULL,
  `mo_carpeta_vc` VARCHAR(255) NULL,
  `mo_tipo_en` ENUM('user','system','modadmin','lang') NOT NULL DEFAULT 'user',
  `mo_desc_tx` TEXT NULL,
  `mo_instalado_ts` INT(30) NULL DEFAULT NULL,
  `mo_habilitado_en` ENUM('true','false') NOT NULL DEFAULT 'true',
  `mo_actualizacionver_vc` VARCHAR(10) NULL,
  `mo_actualiacionurl_tx` TEXT NULL DEFAULT NULL,
  `x_modcat_mc_id_pk` INT(6) UNSIGNED NOT NULL,
  PRIMARY KEY (`mo_id_pk`, `x_modcat_mc_id_pk`),
  INDEX `fk_x_modulos_x_modcat1_idx` (`x_modcat_mc_id_pk` ASC),
  CONSTRAINT `fk_x_modulos_x_modcat1`
    FOREIGN KEY (`x_modcat_mc_id_pk`)
    REFERENCES `cpanet1_db`.`x_modcat` (`mc_id_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 55
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cpanet1_db`.`x_mysql_basededatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpanet1_db`.`x_mysql_basededatos` (
  `my_id_pk` INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `my_nombre_vc` VARCHAR(40) CHARACTER SET 'latin1' COLLATE 'latin1_general_ci' NULL DEFAULT NULL,
  `my_espacioutilizado_bi` BIGINT(50) NULL DEFAULT '0',
  `my_creado_ts` INT(30) NULL DEFAULT NULL,
  `my_borrado_ts` INT(30) NULL DEFAULT NULL,
  `x_cuenta_ac_id_pk` INT(6) UNSIGNED NOT NULL,
  `x_cuenta_x_grupos_ug_id_pk` INT(6) UNSIGNED NOT NULL,
  `x_cuenta_x_grupos_x_cuenta_ac_id_pk` INT(6) UNSIGNED NOT NULL,
  `x_cuenta_x_paquetes_pk_id_pk` INT(6) UNSIGNED NOT NULL,
  `x_cuenta_x_paquetes_x_cuenta_ac_id_pk` INT(6) UNSIGNED NOT NULL,
  PRIMARY KEY (`my_id_pk`, `x_cuenta_ac_id_pk`, `x_cuenta_x_grupos_ug_id_pk`, `x_cuenta_x_grupos_x_cuenta_ac_id_pk`, `x_cuenta_x_paquetes_pk_id_pk`, `x_cuenta_x_paquetes_x_cuenta_ac_id_pk`),
  INDEX `fk_x_mysql_basededatos_x_cuenta1_idx` (`x_cuenta_ac_id_pk` ASC, `x_cuenta_x_grupos_ug_id_pk` ASC, `x_cuenta_x_grupos_x_cuenta_ac_id_pk` ASC, `x_cuenta_x_paquetes_pk_id_pk` ASC, `x_cuenta_x_paquetes_x_cuenta_ac_id_pk` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cpanet1_db`.`x_mysql_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpanet1_db`.`x_mysql_usuarios` (
  `mu_id_pk` INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `mu_nombre_vc` VARCHAR(40) CHARACTER SET 'latin1' COLLATE 'latin1_general_ci' NULL DEFAULT NULL,
  `mu_basededatos` INT(6) NULL DEFAULT NULL,
  `mu_acceso_vc` VARCHAR(40) NULL DEFAULT NULL,
  `mu_clave_vc` VARCHAR(40) NULL DEFAULT NULL,
  `mu_creado_ts` INT(30) NULL DEFAULT NULL,
  `mu_borrado_ts` INT(30) NULL DEFAULT NULL,
  `x_cuenta_ac_id_pk` INT(6) UNSIGNED NOT NULL,
  PRIMARY KEY (`mu_id_pk`, `x_cuenta_ac_id_pk`),
  INDEX `fk_x_mysql_usuarios_x_cuenta1_idx` (`x_cuenta_ac_id_pk` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cpanet1_db`.`x_mysql_bdmap`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpanet1_db`.`x_mysql_bdmap` (
  `mm_id_pk` INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `x_cuenta_ac_id_pk` INT(6) UNSIGNED NOT NULL,
  `x_mysql_basededatos_my_id_pk` INT(6) UNSIGNED NOT NULL,
  `x_mysql_usuarios_mu_id_pk` INT(6) UNSIGNED NOT NULL,
  `x_mysql_usuarios_x_cuenta_ac_id_pk` INT(6) UNSIGNED NOT NULL,
  PRIMARY KEY (`mm_id_pk`, `x_cuenta_ac_id_pk`, `x_mysql_basededatos_my_id_pk`, `x_mysql_usuarios_mu_id_pk`, `x_mysql_usuarios_x_cuenta_ac_id_pk`),
  INDEX `fk_x_mysql_bdmap_x_cuenta1_idx` (`x_cuenta_ac_id_pk` ASC),
  INDEX `fk_x_mysql_bdmap_x_mysql_basededatos1_idx` (`x_mysql_basededatos_my_id_pk` ASC),
  INDEX `fk_x_mysql_bdmap_x_mysql_usuarios1_idx` (`x_mysql_usuarios_mu_id_pk` ASC, `x_mysql_usuarios_x_cuenta_ac_id_pk` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cpanet1_db`.`x_permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpanet1_db`.`x_permisos` (
  `pe_id_pk` INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `x_modulos_mo_id_pk` INT(6) UNSIGNED NOT NULL,
  `x_modulos_x_modcat_mc_id_pk` INT(6) UNSIGNED NOT NULL,
  `x_grupos_ug_id_pk` INT(6) UNSIGNED NOT NULL,
  `x_grupos_x_cuenta_ac_id_pk` INT(6) UNSIGNED NOT NULL,
  PRIMARY KEY (`pe_id_pk`, `x_modulos_mo_id_pk`, `x_modulos_x_modcat_mc_id_pk`, `x_grupos_ug_id_pk`, `x_grupos_x_cuenta_ac_id_pk`),
  INDEX `fk_x_permisos_x_modulos1_idx` (`x_modulos_mo_id_pk` ASC, `x_modulos_x_modcat_mc_id_pk` ASC),
  INDEX `fk_x_permisos_x_grupos1_idx` (`x_grupos_ug_id_pk` ASC, `x_grupos_x_cuenta_ac_id_pk` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 743
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cpanet1_db`.`x_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpanet1_db`.`x_perfil` (
  `ud_id_pk` INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ud_nombrecompleto_vc` VARCHAR(100) NULL DEFAULT NULL,
  `ud_lenguaje_vc` VARCHAR(10) NULL DEFAULT 'en',
  `ud_direccion_tx` TEXT NULL DEFAULT NULL,
  `ud_codigopostal_vc` VARCHAR(20) NULL DEFAULT NULL,
  `ud_telefono_vc` VARCHAR(20) NULL DEFAULT NULL,
  `ud_creado_ts` INT(30) NULL DEFAULT NULL,
  `x_cuenta_ac_id_pk` INT(6) UNSIGNED NOT NULL,
  `x_cuenta_x_grupos_ug_id_pk` INT(6) UNSIGNED NOT NULL,
  `x_cuenta_x_grupos_x_cuenta_ac_id_pk` INT(6) UNSIGNED NOT NULL,
  `x_cuenta_x_paquetes_pk_id_pk` INT(6) UNSIGNED NOT NULL,
  `x_cuenta_x_paquetes_x_cuenta_ac_id_pk` INT(6) UNSIGNED NOT NULL,
  `x_paquetes_pk_id_pk` INT(6) UNSIGNED NOT NULL,
  `x_paquetes_x_cuenta_ac_id_pk` INT(6) UNSIGNED NOT NULL,
  PRIMARY KEY (`ud_id_pk`, `x_cuenta_ac_id_pk`, `x_cuenta_x_grupos_ug_id_pk`, `x_cuenta_x_grupos_x_cuenta_ac_id_pk`, `x_cuenta_x_paquetes_pk_id_pk`, `x_cuenta_x_paquetes_x_cuenta_ac_id_pk`, `x_paquetes_pk_id_pk`, `x_paquetes_x_cuenta_ac_id_pk`),
  INDEX `fk_x_perfil_x_cuenta1_idx` (`x_cuenta_ac_id_pk` ASC, `x_cuenta_x_grupos_ug_id_pk` ASC, `x_cuenta_x_grupos_x_cuenta_ac_id_pk` ASC, `x_cuenta_x_paquetes_pk_id_pk` ASC, `x_cuenta_x_paquetes_x_cuenta_ac_id_pk` ASC),
  INDEX `fk_x_perfil_x_paquetes1_idx` (`x_paquetes_pk_id_pk` ASC, `x_paquetes_x_cuenta_ac_id_pk` ASC),
  CONSTRAINT `fk_x_perfil_x_cuenta1`
    FOREIGN KEY (`x_cuenta_ac_id_pk` , `x_cuenta_x_grupos_ug_id_pk` , `x_cuenta_x_grupos_x_cuenta_ac_id_pk` , `x_cuenta_x_paquetes_pk_id_pk` , `x_cuenta_x_paquetes_x_cuenta_ac_id_pk`)
    REFERENCES `cpanet1_db`.`x_cuenta` (`ac_id_pk` , `x_grupos_ug_id_pk` , `x_grupos_x_cuenta_ac_id_pk` , `x_paquetes_pk_id_pk` , `x_paquetes_x_cuenta_ac_id_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_x_perfil_x_paquetes1`
    FOREIGN KEY (`x_paquetes_pk_id_pk` , `x_paquetes_x_cuenta_ac_id_pk`)
    REFERENCES `cpanet1_db`.`x_paquetes` (`pk_id_pk` , `x_cuenta_ac_id_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cpanet1_db`.`x_cuotas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpanet1_db`.`x_cuotas` (
  `qt_id_pk` INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `qt_dominio_in` INT(6) NULL DEFAULT '0',
  `qt_subdominios_in` INT(6) NULL DEFAULT '0',
  `qt_dominiosreservados_in` INT(6) NULL DEFAULT '0',
  `qt_buzoncorreo_in` INT(6) NULL DEFAULT '0',
  `qt_reenvios_in` INT(6) NULL DEFAULT '0',
  `qt_listdis_in` INT(6) NULL DEFAULT '0',
  `qt_ftpcuentas_in` INT(6) NULL DEFAULT '0',
  `qt_mysql_in` INT(6) NULL DEFAULT '0',
  `qt_espaciodisco_bi` BIGINT(20) NULL DEFAULT '0',
  `qt_anchobanda_bi` BIGINT(20) NULL DEFAULT '0',
  `qt_abhabilitado_in` INT(1) NULL DEFAULT '0',
  `qt_ldhabilitada_in` INT(1) NULL DEFAULT '0',
  `qt_totalab` INT(30) NULL DEFAULT NULL,
  `qt_minab` INT(30) NULL DEFAULT NULL,
  `qt_maxcon` INT(30) NULL DEFAULT NULL,
  `qt_tamanofichero` INT(30) NULL DEFAULT NULL,
  `qt_velocidadfichero` INT(30) NULL DEFAULT NULL,
  `qt_tipofichero_vc` VARCHAR(30) NOT NULL DEFAULT '*',
  `qt_modificado_in` INT(1) NULL DEFAULT '0',
  `x_paquetes_pk_id_pk` INT(6) UNSIGNED NOT NULL,
  `x_anchobanda_bd_id_pk` INT(6) UNSIGNED NOT NULL,
  `x_anchobanda_x_cuenta_ac_id_pk` INT(6) UNSIGNED NOT NULL,
  `x_htaccess_ht_id_pk` INT(11) UNSIGNED NOT NULL,
  `x_htaccess_x_cuenta_ac_id_pk` INT(6) UNSIGNED NOT NULL,
  PRIMARY KEY (`qt_id_pk`, `x_paquetes_pk_id_pk`, `x_anchobanda_bd_id_pk`, `x_anchobanda_x_cuenta_ac_id_pk`, `x_htaccess_ht_id_pk`, `x_htaccess_x_cuenta_ac_id_pk`),
  INDEX `fk_x_cuotas_x_paquetes1_idx` (`x_paquetes_pk_id_pk` ASC),
  INDEX `fk_x_cuotas_x_anchobanda1_idx` (`x_anchobanda_bd_id_pk` ASC, `x_anchobanda_x_cuenta_ac_id_pk` ASC),
  INDEX `fk_x_cuotas_x_htaccess1_idx` (`x_htaccess_ht_id_pk` ASC, `x_htaccess_x_cuenta_ac_id_pk` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cpanet1_db`.`x_configuracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpanet1_db`.`x_configuracion` (
  `so_id_pk` INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `so_nombre_vc` VARCHAR(50) NULL DEFAULT NULL,
  `so_nombrecompleto_vc` VARCHAR(50) NULL DEFAULT NULL,
  `so_valor_tx` TEXT NULL DEFAULT NULL,
  `so_valorpred_tx` TEXT NULL DEFAULT NULL,
  `so_desc_tx` TEXT NULL DEFAULT NULL,
  `so_modulo_vc` VARCHAR(50) NULL DEFAULT NULL,
  `so_usuarioreditable_en` ENUM('true','false') NULL DEFAULT 'false',
  PRIMARY KEY (`so_id_pk`))
ENGINE = InnoDB
AUTO_INCREMENT = 122
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cpanet1_db`.`x_lenguaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpanet1_db`.`x_lenguaje` (
  `tr_id_pk` INT(11) NOT NULL AUTO_INCREMENT,
  `tr_en_tx` TEXT NULL DEFAULT NULL,
  `tr_es_tx` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`tr_id_pk`))
ENGINE = InnoDB
AUTO_INCREMENT = 124
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
